### PR TITLE
Initial implementation

### PR DESCRIPTION
**Pull request by mbaechtold**

### CODE REVIEW

**Comment by mbaechtold** [comment]
This requires https://github.com/4teamwork/ftw.slider/pull/29

**Comment by maethu** [comment]
@mbaechtold  https://github.com/4teamwork/ftw.slider/pull/29 is merged!

**Comment by mbaechtold** [comment]
Thank you @maethu!

**Comment by maethu** [comment]
@mbaechtold pls checkout ftw.slider from source!

**Comment by mbaechtold** [comment]
@maethu: done.

**Comment by maethu** [comment]
@mbaechtold Seems like the arrows are misplaced...
screen shot 2015-06-25 at 15 49 42

They should be aligned within the image not within the hole block.

**Comment by maethu** [comment]
@mbaechtold Title will not be displayed - use the same implementation as in textblock, or sliderblock (title and show title)

**Comment by mbaechtold** [comment]
We need to discuss the positioning of the arrows with @bierik.

**Comment by mbaechtold** [comment]
@maethu: the title is now rendered if the corresponding checkbox is active.

**Comment by maethu** [comment]
Position the arrows is a integration Problem... We move forward with this one.

**Pull request merged**
