### PR TITLE
Strip newlines when rendering the slick config.

### PR DESCRIPTION
**Pull request by mbaechtold**

### CODE REVIEW

**Comment by maethu** [comment]
Tests are broken. Seems like if the field is empty it breaks

**Comment by maethu** [comment]
https://jenkins.4teamwork.ch/view/All/job/ftw.sliderblock-pull-request-11-test-plone-4.3.x.cfg/3/console

**Comment by mbaechtold** [comment]
I'll be looking into this right now.

**Comment by mbaechtold** [comment]
@maethu: green :+1:

**Pull request merged**
